apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: order-container
  name: order-container
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: order-container
  type: LoadBalancer
status:
  loadBalancer: {}
