apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: identity-container
  name: identity-container
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: identity-container
  type: LoadBalancer
status:
  loadBalancer: {}
