apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: profile-container
  name: profile-container
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: profile-container
  type: LoadBalancer
status:
  loadBalancer: {}
